.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OPENERP\-AUTOBUILD" "1" "2017-08-17" "Bluestar Solutions Sàrl" "OpenERP Autobuild"
.
.SH "NAME"
\fBopenerp\-autobuild\fR \- build and run Odoo/OpenERP projects
.
.SH "SYNOPSIS"
\fBopenerp\-autobuild\fR [\-\-version] [\-\-help] \fBoebuild\fR [\-\-version] [\-\-help] \fBopenerp\-autobuild\fR \fIgoal\fR [\-\-help] \.\.\. \fBoebuild\fR \fIgoal\fR [\-\-help] \.\.\.
.
.SH "DESCRIPTION"
A tool to build and run Odoo/OpenERP projects\.
.
.P
The main goals of OpenERP Autobuild are:
.
.IP "\(bu" 4
Improve the collaboration in development teams\.
.
.IP "\(bu" 4
Enable the use of continuous integration solutions\.
.
.IP "" 0
.
.P
Inspired by solutions like composer (http://getcomposer\.org) this tool is made for OpenERP modules developers\. It manages the dependencies and the run goal of your project\. By enabling the possibility to define precisely the revision of OpenERP you want to use in your project and by managing your custom dependencies and their transitive dependencies, it improves teams collaboration on projects ensuring developments and test are made on the same defined version\.
.
.SH "OPTIONS"
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Prints openerp\-autobuild version\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints the synopsis and the list of goals\.
.
.SH "GOALS"
.
.TP
\fBrun\fR
Run Odoo server normally\.
.
.TP
\fBrun\.test\fR
Run Odoo server, perform tests, stop the server and display tests results\.
.
.TP
\fBproject\.init\fR
Initialize an empty Odoo project\.
.
.TP
\fBproject\.version\fR
Set the version of all project modules\.
.
.TP
\fBproject\.assembly\fR
Prepare all files to deploy in target folder\.
.
.TP
\fBmodule\.create\fR
Create a new module\.
.
.TP
\fBeclipse\.init\fR
Initialize an Eclipse PyDev project\.
.
.SH "GOALS OPTIONS"
.
.SS "run"
\fBopenerp\-autobuild\fR run [\-h] [\-A [\fIpath\fR]] [\-u [all|\fImodule1\fR[,\fImodule2\fR…]]] [\-i [all|\fImodule1\fR[,\fImodule2\fR…]]] [\-l] [\-d \fIdatabase\fR] [\-a] \fBoebuild\fR run [\-h] [\-A [\fIpath\fR]] [\-u [all|\fImodule1\fR[,\fImodule2\fR…]]] [\-i [all|\fImodule1\fR[,\fImodule2\fR…]]] [\-l] [\-d \fIdatabase\fR] [\-a]
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage and options for the goal\.
.
.TP
\fB\-d\fR \fIdatabase\fR, \fB\-\-database\fR=\fIdatabase\fR
Database used when installing or updating modules\.
.
.TP
\fB\-u\fR [all|\fImodule1\fR[,\fImodule2\fR\.\.\.]], \fB\-\-update\fR=[all|\fImodule1\fR[,\fImodule2\fR\.\.\.]]
Modules to install\. Don\'t specify any module to use the module list of the current project\. \fB\-\-database\fR is required\.
.
.TP
\fB\-i\fR [all|\fImodule1\fR[,\fImodule2\fR\.\.\.]], \fB\-\-init\fR=[all|\fImodule1\fR[,\fImodule2\fR\.\.\.]]
Modules to update\. Don\'t specify any module to use the module list of the current project\. \fB\-\-database\fR is required\.
.
.TP
\fB\-a\fR, \fB\-\-auto\-reload\fR
Enable auto\-reloading of python files and xml files without having to restart the server\. Requires pyinotify\. Available since Odoo version 8\.0
.
.TP
\fB\-A\fR [\fIpath\fR], \fB\-\-alternate\-config\fR=[\fIpath\fR]
Use an alternate directory to find configuration files instead of /etc and /home/user (for development purpose)\. Don\'t specify \fIpath\fR to use \'\./devconf\' with supplied files\.
.
.TP
\fB\-l\fR, \fB\-\-local\fR
Bypass remote updates checks and try to launch with last parameters\.
.
.SS "run\.test"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage and options for the goal\.
.
.TP
\fB\-d\fR \fIdatabase\fR, \fB\-\-database\fR=\fIdatabase\fR
Database name for tests\.Use autobuild_{PROJECT_NAME} if not specified\.
.
.TP
\fB\-u\fR [all|\fImodule1\fR[,\fImodule2\fR\.\.\.]], \fB\-\-update\fR=[all|\fImodule1\fR[,\fImodule2\fR\.\.\.]]
Modules to install\. Don\'t specify any module to use the module list of the current project\. \fB\-\-database\fR is required\.
.
.TP
\fB\-i\fR [all|\fImodule1\fR[,\fImodule2\fR\.\.\.]], \fB\-\-init\fR=[all|\fImodule1\fR[,\fImodule2\fR\.\.\.]]
Modules to update\. Don\'t specify any module to use the module list of the current project\. \fB\-\-database\fR is required\.
.
.TP
\fB\-A\fR [\fIpath\fR], \fB\-\-alternate\-config\fR=[\fIpath\fR]
Use an alternate directory to find configuration files instead of /etc and /home/user (for development purpose)\. Don\'t specify \fIpath\fR to use \'\./devconf\' with supplied files\.
.
.TP
\fB\-l\fR, \fB\-\-local\fR
Bypass remote updates checks and try to launch with last parameters\.
.
.TP
\fB\-c\fR, \fB\-\-test\-commit\fR
Commit test results in DB\.
.
.TP
\fB\-n\fR, \fB\-\-new\-install\fR
Force new install\. This will delete the database if it exists\.
.
.TP
\fB\-a\fR, \fB\-\-analyze\fR
Analyze log and stop Odoo, exit with status 0 if all test successfully pass, 1 otherwise\. Used for continuous integration\.
.
.TP
\fB\-C\fR, \fB\-\-continue\fR
Continue running Odoo server when tests are done\.
.
.TP
\fB\-D\fR, \fB\-\-drop\-database\fR
Drop used database before exiting\.
.
.SS "project\.init"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage and options for the goal\.
.
.TP
\fB\-A\fR [\fIpath\fR], \fB\-\-alternate\-config\fR=[\fIpath\fR]
Use an alternate directory to find configuration files instead of /etc and /home/user (for development purpose)\. Don\'t specify \fIpath\fR to use \'\./devconf\' with supplied files\.
.
.TP
\fB\-l\fR, \fB\-\-local\fR
Bypass remote updates checks and try to launch with last parameters\.
.
.SS "project\.version"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage and options for the goal\.
.
.TP
\fB\-n\fR [\fIversion\fR], \fB\-\-new\-version\fR=[\fIversion\fR]
The modules new version\.
.
.TP
\fB\-A\fR [\fIpath\fR], \fB\-\-alternate\-config\fR=[\fIpath\fR]
Use an alternate directory to find configuration files instead of /etc and /home/user (for development purpose)\. Don\'t specify \fIpath\fR to use \'\./devconf\' with supplied files\.
.
.TP
\fB\-l\fR, \fB\-\-local\fR
Bypass remote updates checks and try to launch with last parameters\.
.
.SS "project\.assembly"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage and options for the goal\.
.
.TP
\fB\-i\fR, \fB\-\-include\-odoo\fR
Include Odoo/OpenERP in target\.
.
.TP
\fB\-A\fR [\fIpath\fR], \fB\-\-alternate\-config\fR=[\fIpath\fR]
Use an alternate directory to find configuration files instead of /etc and /home/user (for development purpose)\. Don\'t specify \fIpath\fR to use \'\./devconf\' with supplied files\.
.
.TP
\fB\-l\fR, \fB\-\-local\fR
Bypass remote updates checks and try to launch with last parameters\.
.
.SS "module\.create"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage and options for the goal\.
.
.TP
\fB\-L\fR [\fIlong\-name\fR], \fB\-\-long\-name\fR=[\fIlong\-name\fR]
The module long name\.
.
.TP
\fB\-c\fR [\fIcategory\fR], \fB\-\-category\fR=[\fIcategory\fR]
The module long name\.
.
.TP
\fB\-A\fR [\fIpath\fR], \fB\-\-alternate\-config\fR=[\fIpath\fR]
Use an alternate directory to find configuration files instead of /etc and /home/user (for development purpose)\. Don\'t specify \fIpath\fR to use \'\./devconf\' with supplied files\.
.
.TP
\fB\-l\fR, \fB\-\-local\fR
Bypass remote updates checks and try to launch with last parameters\.
.
.SS "eclipse\.init"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints usage and options for the goal\.
.
.TP
\fB\-A\fR [\fIpath\fR], \fB\-\-alternate\-config\fR=[\fIpath\fR]
Use an alternate directory to find configuration files instead of /etc and /home/user (for development purpose)\. Don\'t specify \fIpath\fR to use \'\./devconf\' with supplied files\.
.
.TP
\fB\-l\fR, \fB\-\-local\fR
Bypass remote updates checks and try to launch with last parameters\.
.
.SH "FAQ"
.
.SS "Where Odoo/OpenERP is installed ?"
It is located in a workspace outside of the project\. By default /var/oebuild/[your\-project\-name]/openerp
.
.P
You can override the default value (~/tec/oebuild_config\.json) in your user configuration file (~/\.config/openerp\-autobuild/oebuild_config\.json)\.
.
.SS "Where is the code of my project dependencies ?"
It is in a workspace outside of the project\. By default : /var/oebuild/[your\-project\-name]/deps
.
.P
You can override the default value (~/tec/oebuild_config\.json) in your user configuration file (~/\.config/openerp\-autobuild/oebuild_config\.json)\.
.
.SS "Is OpenERP Autobuild compatible with previous versions ?"
OpenERP Autobuild configuration files are not compatible with previous version, but OpenERP Autobuild will automatically update your project configuration files\. If dependencies have previous configuration files autobuild will update these in the workspace to use it\.
.
.SH "AUTHORS"
OpenERP Autobuild was started an maintained by Bluestar Solutions Sàrl (\fIhttp://www\.blues2\.ch\fR), an Odoo partner who develops custom\-made modules\.
.
.P
Project and sources: \fIhttps://github\.com/bluestar\-solutions/openerp\-autobuild\fR
.
.SH "COPYRIGHT"
Copyright (C) 2012\-2015 Bluestar Solutions Sàrl (\fIhttp://www\.blues2\.ch\fR)\. Released under GNU AGPLv3\.
